### ISSUE TITLE
Table query parameters don't allow for just `scope` querying

### ISSUE THREAD

**Issue by aaroncox** [wharfkit/contract#20]
The following syntax, when we just need to query by scope (with no lower/upper bounds) is a bit odd.

```ts
const rows = await contract
    .table('delband')
    .query(
        {
            from: '',
            to: '',
        },
        {
            scope: 'wharfkittest',
        }
    )
    .all()
```

Going back to this discussion: 

https://github.com/wharfkit/contract/pull/3#discussion_r1240240190

Specifically this recommendation:

```ts
decentiumTable.query({
    from: 101511,
    to: 105056,
    scope: 'decentiumorg'
    index: 'score'
})
```

I think we just need one parameter, where everything is optional. Then, in the original odd code snippet I shared at the top of this issue, we'd just simply be able to do:

```ts
const rows = await contract
    .table('delband')
    .query({
        scope: 'wharfkittest',   
    })
    .all()
```

**Comment by dafuga** [comment]
Makes sense!
