### ISSUE TITLE
[Contract kit] - get_table_by_scope query

### ISSUE THREAD

**Issue by david-at-greymass** [wharfkit/contract#47]
One thing we haven’t addressed in the Contract Kit is `get_table_by_scope.`
```
curl 'https://eos.greymass.com/v1/chain/get_table_by_scope' --data-raw '{"code":"eosio.msig","table":"proposal"}'
```

It returns all the scopes you could query from the table.

![Image](https://github.com/wharfkit/contract/assets/139813631/f446fe94-e4e9-4133-88cd-73ad100001e4)

Trying to think of what the syntax would be for this, which I imagine would be on a `Table` instance, like…

```
await contract.table('proposal').scopes().next()
```

**Comment by aaroncox** [comment]
Related PR: https://github.com/wharfkit/contract/pull/48
